// flow-typed signature: 4697302ca2c6d939680c3c9f5b3f58bc
// flow-typed version: <<STUB>>/@types/node_v^12.12.14/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
